---
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Introduction

Welcome to STA 6233. In this course you will learn the basics of R, but we will not stop there. This course is designed to be pragmatic and give you the real world tools you will need to secure a job or further your academic career. With that in mind, this document is designed to give you a head start into the course materials and solidify your foundation in coding and in R. I am providing videos and reading materials below that are all accessible online. Please take advantage of these as they will assist your understanding of R basics and allow us to more quickly get to the meat of the course and provide you with a robust understanding of pratical R coding skills.

We will also refer to some of this material throughout the course so do not feel like you have to go through it all now. This is especially true for the cheat sheets. I look forward to teaching you all this semester! Relax, and breath, we will get through this together and if you give maximum effort in this course your grade will reflect it.

### **Videos**

*Introduction to R and RStudio*  
  https://youtu.be/lL0s1coNtRk

*Introduction to Data Science with R - Data Analysis Part 1*  
  https://youtu.be/32o0DnuRjfg

*R Programming Tutorial - Learn the Basics of Statistical Computing*  
  https://youtu.be/_V8eKsto3Ug

### **Readings**
  *R Cookbook*  
  http://www.cookbook-r.com/
  
  *R Cookbook v2*  
  https://rc2e.com/
  
  *R Graphics Cookbook*  
  https://r-graphics.org/
  <br/>
  
### **Cheat Sheets**
  *Base R*  
  https://rstudio.com/wp-content/uploads/2016/10/r-cheat-sheet-3.pdf
  
  *Data Import*  
  https://rawgit.com/rstudio/cheatsheets/master/data-import.pdf
  
  *dplyr and tidyr*  
  https://rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf

  *R Markdown*  
  https://rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf  
  
  *String Manipulation*  
  https://github.com/rstudio/cheatsheets/blob/master/strings.pdf  
  
  *Other Cheatsheets*  
  https://rstudio.com/resources/cheatsheets/  
  
#### **Singer and Willet Real World Examples with Code**
  https://stats.idre.ucla.edu/other/examples/alda/  
  

